### ISSUE TITLE
Bad object key string

### ISSUE THREAD

**Issue by n0ct1s-k8sh** [spacechunks/packer-plugin-s3#4]
# Background
When you try to download an object, it fails printing a 404 (_Not Found_) error.

```
==> Some builds didn't complete successfully and had errors:
--> docker.my-image: error downloading object /base/dir1/dir2/myobject.txt: operation error S3: GetObject, https response error StatusCode: 404, RequestID: XXXXXXXXXXXXXXXXX, HostID: XXX/XXXXXXXXXX/XXXXXXXXXXXX/XXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXX, NoSuchKey:
```

The provisioner has been called correctly:
```hcl
provisioner "s3" {
  profile = "myprofile"
  objects {
    source = "thebucket/base/dir1/dir2/myobject.txt"
    destination = "/tmp/myobject.txt"
  }
}
```

# Diagnosis
If you try to reproduce this with the AWS CLI and S3 API, you'll get the same:
```shell
vscode ➜ /workspaces/…/work (master) $ aws s3api get-object --bucket thebucket --profile myprofile --key /base/dir1/dir2/myobject.txt myobject.txt

An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

But if you remove the `/` at the beginning, it works:
```shell
vscode ➜ /workspaces/…/work (master) $ aws s3api get-object --bucket thebucket --profile myprofile --key base/dir1/dir2/myobject.txt myobject.txt 
{
    "AcceptRanges": "bytes",
    "LastModified": "2024-07-12T11:27:53+00:00",
    "ContentLength": 25779,
    "ETag": "\"XXXXXXXXXXXXXXXX\"",
    "VersionId": "XXXXXXXXXXXXXX",
    "ContentType": "text/plain",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

# Conclusion
It seems that the object path is malformed because of the `/` at the beginning. [Here is the line](https://github.com/spacechunks/packer-plugin-s3/blob/main/provisioner.go#L115C37-L115C40)

**Comment by n0ct1s-k8sh** [comment]
I cannot clone and fix this for myself due to libraries and dependencies issues. Is it ok if I create a devcontainer environment and include it in the PR?

**Comment by freggy** [comment]
hey @n0ct1s-k8sh, no need to fix this yourself :) I removed the offending lines and tested it again and now it should be working. I created a `v2.0.1` release containing the fix.
